title: DSA & DEV
description: Data Structures & Algorithm and Development Community
google_analytics: UA-246694719-1
show_downloads: true
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins
show_downloads: false