title: DSA & DEV
description: Data Structures & Algorithm and Development Community
google_analytics: G-ZY3LCZT0EF
show_downloads: true
google_analytics: 
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins
show_downloads: false